<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pizzaria.Application\Pizzaria.Application.csproj" />
    <ProjectReference Include="..\Pizzaria.Infrastructure\Pizzaria.Infrastructure.csproj" />
  </ItemGroup>

</Project>
